### HomeWork 12

In [2]:
import pandas as pd
import numpy as np

### Q1.

```
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```
**Write code to convert the above mydict variable into dataframe , your code should return a dataframe like below.**

```
a    0
b    1
c    2
d    4
```

In [16]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

df_q1 = pd.DataFrame(list(mydict.items()), columns=['letter', 'number'])
df_q1

   letter  number
0       a       0
1       b       1
2       c       2
3       e       3
4       d       4
5       f       5
6       g       6
7       h       7
8       i       8
9       j       9
10      k      10
11      l      11
12      m      12
13      n      13
14      o      14
15      p      15
16      q      16
17      r      17
18      s      18
19      t      19
20      u      20
21      v      21
22      w      22
23      x      23
24      y      24
25      z      25

### Q2. Write the code to get frequency count of each character from the result of below command
```
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
```

In [17]:
## your output should look like this.
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

freq_q2 = ser.value_counts()
freq_q2

a    8
d    6
b    6
e    4
f    2
h    2
g    1
c    1
Name: count, dtype: int64

### Q3. What parameter to do we need to add in read_csv, which let us read only a bunch of columns from the whole dataset.

In [33]:
# just write that parameter name here
df_subset = pd.read_csv("E:\\Masters Data Analytics\\MSDA-class-work\\DATA-200\\Files\\fruits.csv", usecols=['Fruit Name', 'Price'])
df_subset

   Fruit Name  Price
0      Banana    112
1       Mango    160
2      Banana     85
3   PineApple     90
4  Strawberry    200
5       Mango     60
6       Mango    100
7   PineApple    285

<p style="color:brown;">For Next 3 question you need to work on fruits sample dataset provided in resources.</p>

In [6]:
# read fruits.csv file

### Q4. Get mean, median, max , min price for each fruit .

In [35]:
# Your output should look like this
stats_q4 = df_subset.groupby('Fruit Name')['Price'].agg(['mean', 'median', 'max', 'min'])
stats_q4

                  mean  median  max  min
Fruit Name
Banana       98.500000    98.5  112   85
Mango       106.666667   100.0  160   60
PineApple   187.500000   187.5  285   90
Strawberry  200.000000   200.0  200  200

### Q5. What is the total cost of this basket?

In [38]:
df = pd.read_csv("E:\\Masters Data Analytics\\MSDA-class-work\\DATA-200\\Files\\fruits.csv")

total_cost_q5 = (df['Price'] * df['Quantity']).sum()
total_cost_q5

np.int64(57936)

### Q6. Which fruit has the maximum price per quantity?

In [39]:
df['price_per_qty'] = df['Price'] / df['Quantity']
max_fruit_q6 = df.loc[df['price_per_qty'].idxmax()]
max_fruit_q6

Fruit Name       PineApple
Quantity                15
Price                   90
price_per_qty          6.0
Name: 3, dtype: object

### Q7. Given an array 
```arr = [ 0,1,0,1,0,2,3,6,5,0,0,0,4,1,2,3,5,5,4,4 ]```
<br>
**Write code to  Create one_hot encoded dataframe of this array.**

In [26]:
#your output should be like this and should have 20 records in total
import pandas as pd

arr = [0,1,0,1,0,2,3,6,5,0,0,0,4,1,2,3,5,5,4,4]

df_q7 = pd.get_dummies(arr)
df_q7

        0      1      2      3      4      5      6
0    True  False  False  False  False  False  False
1   False   True  False  False  False  False  False
2    True  False  False  False  False  False  False
3   False   True  False  False  False  False  False
4    True  False  False  False  False  False  False
5   False  False   True  False  False  False  False
6   False  False  False   True  False  False  False
7   False  False  False  False  False  False   True
8   False  False  False  False  False   True  False
9    True  False  False  False  False  False  False
10   True  False  False  False  False  False  False
11   True  False  False  False  False  False  False
12  False  False  False  False   True  False  False
13  False   True  False  False  False  False  False
14  False  False   True  False  False  False  False
15  False  False  False   True  False  False  False
16  False  False  False  False  False   True  False
17  False  False  False  False  False   True  False
18  False  False  False  False   True  False  False
19  False  False  False  False   True  False  False

### Q8. 
```
dict_ = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]

```
#### a. Convert this above dict to pandas dataframe

In [27]:
#your output should be like this
dict_ = {
    'First Score':[100, 90, np.nan, 95],
    'Second Score': [30, 45, 56, np.nan],
    'Third Score':[np.nan, 40, 80, 98]
}

df_q8 = pd.DataFrame(dict_)
df_q8

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

#### b. Write code to get the number of missing values for each column.

In [28]:
#your output should be like this 
missing_q8 = df_q8.isna().sum()
missing_q8

First Score     1
Second Score    1
Third Score     1
dtype: int64

#### c. Fill this nan values with mean value of their respective column

In [29]:
#your output should be like this
filled_q8 = df_q8.fillna(df_q8.mean(numeric_only=True))
filled_q8

   First Score  Second Score  Third Score
0        100.0     30.000000    72.666667
1         90.0     45.000000    40.000000
2         95.0     56.000000    80.000000
3         95.0     43.666667    98.000000

### Q9. Add an index column to the table used in Q4.
*HINT : Rest index*

In [40]:
stats_q9 = stats_q4.reset_index()
stats_q9

   Fruit Name        mean  median  max  min
0      Banana   98.500000    98.5  112   85
1       Mango  106.666667   100.0  160   60
2   PineApple  187.500000   187.5  285   90
3  Strawberry  200.000000   200.0  200  200

### Q10. 
**You are provided wih two different csv files ,**
```
sample_sheet_1.csv
sample_sheet_2.csv 
```
<p>
    
**You just need to read both of them , and merge them based on location column.**

In [44]:
#your output should be like this
df1 = pd.read_csv("E:\\Masters Data Analytics\\MSDA-class-work\\DATA-200\\Files\\sample_sheet_1.csv")
df2 = pd.read_csv("E:\\Masters Data Analytics\\MSDA-class-work\\DATA-200\\Files\\sample_sheet_2.csv")

merged_q10 = pd.merge(df1, df2, on="Location")
merged_q10

,Location,Population,House_count,Location Area,No. of shops,Weekly market day
0,ABB,2.5 lakh,763,25 hectare,150,Nothing as such
1,ABC,1.5 lakh,520,20 hectare,120,Tuesday
2,CDD,3.5 lakh,800,35 hectare,180,Wednesday